### ISSUE TITLE
Error "There is no working folder" when trying to install a nuget package

### ISSUE THREAD

**Issue by DarryStonem** [NuGet/Home#1004]
When I'm trying to add the Unity prerelease (or any other else) package, Visual Studio 2015 Enterprise show me "There is no working folder mapping for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\lib\portable-net4+sl5+netcore45+wpa81+wp8".

Also, an error for permissions like this "\packages\Unity.3.5.1405-prerelease\lib\portable-net45+wp80+win8+wpa81+MonoAndroid10+MonoTouch10\Microsoft.Practices.Unity.dll could not be found in your workspace, or you do not have permission to access it."

I'm using nugget 3.0.0 and the latest release of Visual Studio 2015 Enterprise, launched yesterday.

**Comment by Alex-Sokolov** [comment]
+1 the same when trying to update package... updating fails

**Comment by ArneKlein** [comment]
I have the same problem. After the installation of Visual Studio 2015 RTM NuGet gave me the same messages as DarryStonems. However, I only got those message with TFS projects. In new projects the installation and update worked flawlessly.

I thought maybe it was because NuGet finally retired the "old way" of using package restore and therefore used owns tools for the migration (https://github.com/owen2/AutomaticPackageRestoreMigrationScript). After I ran the powershell scripts for the cleanup and the migration the first message changed. It now points to "C:\Windows\system32\tools":
![image](https://cloud.githubusercontent.com/assets/5556282/8855814/7da4df88-3167-11e5-8377-9f694740c27b.png)

**Comment by emgarten** [comment]
@DarryStonem can you provide some repro steps to help here? 
Are you installing with the NuGet UI or the powershell console?

**Comment by ChrisRollason** [comment]
Same issue here Windows 8.1, Visual Studio 2015 Community Edition. (This is at home)
Brand new ASP.Net project.   I can add some nuget packages to the solution (knockoutjs, moment).  Others fail (like Tweetsharp).

Get the error in the output
"could not be found in your workspace, or you do not have permission to access it."  

with "The Path is not a legal form" error (https://github.com/NuGet/Home/issues/1010)

At work I tried the same steps (Windows 8.0), Visual Studio Enterprise 2015 and it is working fine there (at the moment).

Both installing from the UI.

**Comment by ArneKlein** [comment]
It seems to me as the mentioned errors are actually separate. 

I could resolve the first error message by removing the NuGet.exe from the .nuget folder. After doing the migration the file was deleted from my solution but not from source control so it continued to exist in the folder but wasn't visible from the solution.

The second message still continues to appear. This seems to by related to "NuGet in VS 2015 ignores disableSourceControlIntegration config setting." https://github.com/NuGet/Home/issues/980

**Comment by yishaigalatzer** [comment]
@emgarten why is this issue assigned to @csharpfritz  ?

**Comment by emgarten** [comment]
@yishaigalatzer not sure.

We should verify that this is fixed as part of https://github.com/NuGet/Home/issues/980

**Comment by emgarten** [comment]
@DarryStonem are you running nuget from an account without a %userprofile%?

**Comment by zhili1208** [comment]
verified this with latest build, can't repro it

**Comment by feiling** [comment]
Verified fixed. Here are the steps to repro:
- Use dev12, create a project, check it into TFS.
- Install a package. Then "Enable NuGet Package Restore" on the solution. Note that this feature is only available in old versions of NuGet.
- Check it changes.
- Exit dev12
- Now open the solution in Dev14. Install a package. Without the fix you'll get error messages like "There is no working folder mapping for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE".

**Comment by khaled-Umar** [comment]
I have the same issue with Windows 10 , VS 2015 enterprise NuGet 3.1.1.0
is solved or still?

**Comment by yishaigalatzer** [comment]
Solved in 3.2RC, check out blog for download and more info.

**Comment by NaomiN** [comment]
I have the same problem with Scaffolding in VS 2015 Windows 10. Here is more info 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/d34b2a50-8f2e-42e7-b4ee-135edf75f82a/visual-studio-2015-scaffolding-is-not-working?forum=visualstudiogeneral

What should I do to resolve the problems?

**Comment by yishaigalatzer** [comment]
This is a link to the rc release that is supposed to fix it http://blog.nuget.org/20150902/nuget-3.2RC.html

**Comment by NaomiN** [comment]
I've installed the file from that blog post but I'm still getting this
Package Manager Console Host Version 3.2.0.10488

Type 'get-help NuGet' to see all available NuGet commands.

Set-DefaultScaffolder : Cannot get an instance of EnvDTE.DTE
At C:_Siriusware\Main\SysManager\packages\T4Scaffolding.Core.1.0.0\tools\init.ps1:50 char:9

What should I do to be able to successfully scaffold as I used to do in VS 2013?

**Comment by yishaigalatzer** [comment]
Are you using mvcscaffolding? Or is it a different package?

**Comment by yishaigalatzer** [comment]
Oh wait, sorry. It is t4 scaffolding. My guess is that this package is not compatible with visual studio 2015. I'll try and reach the package owner

**Comment by NaomiN** [comment]
Yishai, thanks a lot. So far none of our developers can use it in VS 2015. It would be great if you can help us.

**Comment by yishaigalatzer** [comment]
I reached out. Last time around my old team fixed the scaffolding package for visual studio 2013, and it had to do with the package taking dependency on an older visual studio dlls that are no longer supported. This might be a similar issue (at least looks like it from the info). This doesn't seem to be the same issue reported on top, or a nuget issue. But will keep an eye on this with the owners.

**Comment by NaomiN** [comment]
Just in case - here is a Connect issue on that topic I opened

https://connect.microsoft.com/VisualStudio/feedbackdetail/view/1798314/scaffolding-no-longer-working
