### ISSUE TITLE
Cannot install package that contains no libs in VS2015

### ISSUE THREAD

**Issue by citizenmatt** [NuGet/Home#1021]
The new client in VS2015 refuses to install the `JetBrains.ReSharper.SDK` package, or more specifically, one of it's dependencies - [`JetBrains.ExternalAnnotations`](https://www.nuget.org/packages/JetBrains.ExternalAnnotations/), with the error message:

> Could not install package 'JetBrains.ExternalAnnotations 9.1.0.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The package is hidden, and contains XML files to provide data for ReSharper, both at runtime, and when running tests. There are no lib folders, and no assemblies to reference. The `JetBrains.ReSharper.SDK` and all of its packages install with no problems in VS2013.

**Comment by derigel23** [comment]
According to http://blog.nuget.org/20141001/targetframeworkfiltering.html our package has no framework constraints and should be installed fine.

**Comment by pshelton-skype** [comment]
We have a similar-sounding issue with a private NuGet package with the following structure:

```
 Volume in drive C is Local Disk
 Volume Serial Number is 1273-1B62

 Directory of MdmMetrics

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM               720 MdmMetricsExtension.nuspec
08/12/2015  12:07 PM    <DIR>          MetricsExtension
08/12/2015  12:07 PM                 0 out.txt
08/12/2015  12:07 PM    <DIR>          package
08/12/2015  12:07 PM               743 [Content_Types].xml
08/12/2015  12:07 PM    <DIR>          _rels
               3 File(s)          1,463 bytes

 Directory of MdmMetrics\MetricsExtension

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM             4,279 ClientAggregatedMetrics.man
08/12/2015  12:07 PM         5,598,880 cpprest120_2_6.dll
08/12/2015  12:07 PM        61,935,616 cpprest120_2_6.pdb
08/12/2015  12:07 PM           625,664 MetricsExtension.Native.exe
08/12/2015  12:07 PM        10,989,568 MetricsExtension.Native.pdb
08/12/2015  12:07 PM               186 MonAgent-Pkg-Manifest.xml
08/12/2015  12:07 PM           660,128 msvcp120.dll
08/12/2015  12:07 PM           963,232 msvcr120.dll
08/12/2015  12:07 PM               250 start.bat
               9 File(s)     80,777,803 bytes

 Directory of MdmMetrics\package

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM    <DIR>          services
               0 File(s)              0 bytes

 Directory of MdmMetrics\package\services

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM    <DIR>          metadata
               0 File(s)              0 bytes

 Directory of MdmMetrics\package\services\metadata

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM    <DIR>          core-properties
               0 File(s)              0 bytes

 Directory of MdmMetrics\package\services\metadata\core-properties

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM               804 fa77e6f72fa74c998ad3ff655605d38a.psmdcp
               1 File(s)            804 bytes

 Directory of MdmMetrics\_rels

08/12/2015  12:07 PM    <DIR>          .
08/12/2015  12:07 PM    <DIR>          ..
08/12/2015  12:07 PM               504 .rels
               1 File(s)            504 bytes

     Total Files Listed:
              14 File(s)     80,780,574 bytes
              20 Dir(s)  62,341,849,088 bytes free
```
As you can see, it also contains no framework constraints (and installs properly in VS 2013), but fails in VS 2015:
>PM> Install-Package MdmMetricsExtension -Project WorkerRole1 -Version 1.12
Attempting to gather dependencies information for package 'MdmMetricsExtension.1.12.0' with respect to project 'WorkerRole1', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'MdmMetricsExtension.1.12.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'MdmMetricsExtension.1.12.0'
Resolved actions to install package 'MdmMetricsExtension.1.12.0'
Install failed. Rolling back...
Package 'MdmMetricsExtension 1.12' does not exist in project 'WorkerRole1'
Package 'MdmMetricsExtension 1.12' does not exist in folder 'C:\Users\<REDACTED>\Desktop\New folder\AzureCloudService1\packages'
Install-Package : Could not install package 'MdmMetricsExtension 1.12.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package MdmMetricsExtension -Project WorkerRole1 -Version 1.1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

A possible workaround appears to be changing the directory name of the "MetricsExtension" folder to "content", which enables installation to succeed, but which copies references incorrectly.

**Comment by lukepuplett** [comment]
Why is this closed?

I'm struggling to see how the three commits fix the issue. The commits concern _._ empty contentFiles folders. The contentFiles feature is only for project.json projects.

I am trying to create a private package with just files and its failing to install on VS2015 with NuGet 3.4.4.1321.

http://stackoverflow.com/questions/39022761/how-do-i-create-a-nupkg-that-just-contains-files

**Comment by rrelyea** [comment]
@lukepuplett  - can you please open a new issue with details, and link to this one.

**Comment by lukepuplett** [comment]
Hi Rob, thanks for the prompt response. I've given up on it, sorry. Obviously, I found it tough going, but I've had a change of heart as to using a NuGet package in the way I was going to use it, I think a Git submodule or some TeamCity trick will be a better solution.

**Comment by nexussays** [comment]
To anyone else encountering this bug (which is not fixed, despite the issue being closed) who discovers this thread after tearing your hair out searching for a solution:

All you have to do is add a dummy file to /lib. (e.g. I'm generating XML documentation with my project so I just add that in the nuspec: `<file src="..\bin\Release\AnyCPU\ProjectName.xml" target="lib" />`)

See: http://stackoverflow.com/a/38221710/52479

**Comment by derigel23** [comment]
Yeah, the same solution for me - but better to place special file maker (empty directory) `_._`

**Comment by GrowSharp** [comment]
I also don't understand why is this marked as closed. It's obviously still not a problem. 
@deepakaravindr Could you please re-open this?

**Comment by lukepuplett** [comment]
> can you please open a new issue with details, and link to this one.

@GrowSharp Back in 2016 @rrelyea was suggesting a new issue and linking, so try that if it's still a problem in 2021.
