### ISSUE TITLE
VS2015 : Updating from one feed fails for packages from different feed.

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1181]
_From @ralfverstappen on July 24, 2015 7:33_

We have two nuget feeds.
The default NuGet Offical feed and our own locally hosted feed for our own packages.
We package our libraries and push them to our feed.
From VS2013 we run a command in the package manager console to update packages from only our own feed by specifying the source (Update-Package -Source 'NAME OF OUR SOURCE').
This will update only our own packages.
This worked fine in VS2013.
In VS2015 this doesn't work anymore. We get an error on packages that are not from our source:

Update-Package : Package 'EntityFramework' is not foundAt line:1 char:1
+ Update-Package -Source 'NAME OF OUR SOURCE'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Anybody know how to update only from one source using the package manager console?

_Copied from original issue: NuGet/NuGetGallery#2593_

**Comment by yishaigalatzer** [comment]
@ralfverstappen is your expectation that this will update only the packages available on the specified source? 

This seems like it was an undocumented (and perhaps unexpected behavior), will take a deeper look at this to decide what is the actual desired behavior.

Are you packages following some wildcards, so you could use piping?

**Comment by ralfverstappen** [comment]
Yes, I would like to only update available packages and ignore others (VS2013 shows a message that there is now update available for these other packages).
We like to keep up with our own internal packages, but do not update 'external' libraries each time.

How would piping work? What will the command look like?
Do you mean wildcards if that filters all our own packages?

Our packages do not all start with our company name.
We could change this, but it will be a lot of work (including all dependencies between packages).

**Comment by yishaigalatzer** [comment]
@ralfverstappen thanks, that makes sense. I agree with your comments (and insights on using wildcards).

We probably need a flag to update (top level packages) only from your sources, but you got to keep in mind that it might triggered public sub dependencies to be updated as well.

**Comment by ralfverstappen** [comment]
You mean a flag that can be passed with the update statement to make sure it does not fail for packages that are not available in that feed? That would be great.

Not sure whether I understand your last remark about 'trigger(ed) public sub dependencies'.
Can you explain that a little more?

**Comment by yishaigalatzer** [comment]
Imagine you update private package a that depends on a newer version of entityframework available on nuget.org. Updating that say from 5->6 might trigger more updates that are not immediately expected.

**Comment by wilson0x4d** [comment]
@yishaigalatzer removed from thread -- submitted Issue #1591 for consideration instead.

Thanks.

**Comment by yishaigalatzer** [comment]
@wilson0x4d This comment makes sense but does not belong in this issue that talks about the package management console. The scope of this bug is to restore vs2013 behavior. Please open a separate issue to start a discussion.

**Comment by ralfverstappen** [comment]
@yishaigalatzer Thanks for the explanation.

**Comment by johnataylor** [comment]
This is also a problem if you remove a feed. And also if a package you have installed happens to be removed a feed.

**Comment by johnataylor** [comment]
#1266 is a separate issue but impacts this scenario.

**Comment by johnataylor** [comment]
fixed checked in

**Comment by johnataylor** [comment]
NuGet/NuGet.PackageManagement@7bdc2ea399997e480f6db2a5b5f8008e813e1d28

**Comment by RanjiniM** [comment]
Verified as working

**Comment by wilson0x4d** [comment]
As of "3.2.0.10516" this still appears broken. Is the expectation that '10516' has the intended behavior or are we still waiting for an updated VSIX?

Thanks.

```
Package Manager Console Host Version 3.2.0.10516

Type 'get-help NuGet' to see all available NuGet commands.

PM> update-package -Source PrivateCorporateFeed
Attempting to gather dependencies information for multiple packages with respect to project 'PrivateCorp.AppServer.Tests', targeting '.NETFramework,Version=v4.5.2'
update-package : Package 'CommonServiceLocator' is not found
At line:1 char:1
+ update-package -Source PrivateCorporateFeed
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

PM> 
```

**Comment by ralfverstappen** [comment]
I am also curious if this should work (also tested it in VS2015 with updated nuget and still receive an error).
Or do I need to specify a flag for this behaviour?

**Comment by wilson0x4d** [comment]
@ralfverstappen possibly related, where Milestone is "Client-vNext": https://github.com/NuGet/Home/issues/1591

**Comment by ralfverstappen** [comment]
Mmm, just noticed something I never realized (and by coincedence never happened before):
when updating with a specified source in VS2013 it is still possible that 'external' packages are updated.
This happens when the nuget cache contains a newer version for an external package. This package is also updated in the projects.
This makes our strategy for updating local packages with the package manager console even less attractive...
We might resort to using the UI to update all packages for a given source.
