### ISSUE TITLE
NuGet should enable contract based portable profiles to install in contract based frameworks like DNXCore50

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1749]
Currently there is an inconsistency between DNX and NuGet in this regard, DNX allows the installation of portable-(>=net45)+(>=win8) when targeting DNXCore50 or dotnet*.  See related issue: https://github.com/dotnet/corefx/issues/4448

I agree that this is a hack, because it is hard to know what the package author meant when they wrote portable-net45+win8.  If that package meant `windows` and actually P-Invokes that won't work on all DNXCore50 and dotnet projects since those projects run cross-platform.

The problem is that not having this hack breaks the ecosystem.  All the existing packages that didn't mean windows and are pure portable libraries won't install even though they would just work on the new platforms.

This is detrimental and will hurt adoption of DNXCore50 and dotnet.  We need a stop-gap that lets folks get unblocked using those old packages until the package authors can react to update their packages.

`imports` in the project.json was supposed to be this stop-gap.  It allows the project owner to override NuGet and tell it to consider specific target monikers that it otherwise would not.  This works for TFM-specfic projects eg:   `"frameworks": {
    "dnxcore50": {
      "imports": "portable-net45+win8"
    }
  }` but does not work for portable projects `"frameworks": {
    "dotnet5.4": {
      "imports": "portable-net45+win8"
    }
  }`.

The problem here is that the graph-walks for guardrails are not honoring the import statement.  I propose that we change gaurdrails to consider the import statement.  This should be non-breaking since imports will be evaluated last in the TFM fallbacks.

**Comment by Pilchie** [comment]
Tagging @davidfowl too

**Comment by yishaigalatzer** [comment]
Looks reasonable to me. Lets discuss the design with @davidfowl

**Comment by emgarten** [comment]
@ericstj how does this fit with netstandard?

**Comment by ericstj** [comment]
It fits with NETStandard just fine.  Gaurdrails are still an option for NETStandard projects.  It's less mainstream though.  The plan for NETStandard is the default behavior will be for the compat check to only look at the NETStandard graph (RID-less graph) for its compat check.  If that fails then a library author can add gaurdrails to constrain to specific platforms.

**Comment by yishaigalatzer** [comment]
@ericstj and @davidfowl, can we drop this issue? I'm not sure how much we can about dnxcore50 anymore, I don't want to create legacy for TFMs we only had in pre-release products

**Comment by yishaigalatzer** [comment]
Folks what is the current experience, I believe this should work with netstandard, but not sure if it does at the moment or not. Did someone test this already?

Moving to CLI RC-2, and we will either fix it then, or it is already fixed and will get closed :)

**Comment by ericstj** [comment]
It works for packages that use `netstandard` but not for those that use `portable-net45+win8`.  The point of this issue was to address the problem with `portable-net45+win8`.

**Comment by yishaigalatzer** [comment]
Even with the import tag?

**Comment by ericstj** [comment]
Import still doesn't work for `supports` txm/RID-based graph walks.  We need those to work even if we move the compat checks out of NuGet.

**Comment by emgarten** [comment]
I see the supports section as specifying a list of TxMs that the project is guaranteed to work with after being packed into a nupkg.

Allowing imports for guardrails means that you are verifying that a nupkg can be built that will work the TxM + imports, which is fine, but users have no way of knowing what imports they should have when they install the package. They will get a restore failure at first and think that the package doesn't work for their project TxM until they discover that it requires imports.

**Comment by ericstj** [comment]
That's true in general for imports.  If I create a NETStandard library and import portable-net45+win8 and use some package that relies on that import (eg: xunit) then folks using my package will need the import as well.

**Comment by emgarten** [comment]
@ericstj doesn't that defeat the point of guard rails, which is to help create a package for a specific TxM?

**Comment by yishaigalatzer** [comment]
We are not going to float imports through packages, the idea is  to force downstream packages to enable netstandard and not carry legacy forward

**Comment by emgarten** [comment]
@ericstj is there still work needed for this?

**Comment by rrelyea** [comment]
@ericstj  - assuming this isn't an important issue anymore. please ping if it is and we'll reopen. "NuGet should enable contract based portable profiles to install in contract based frameworks like DNXCore50"
