### ISSUE TITLE
Release Notes in the Package Manager UI 

### ISSUE THREAD

**Issue by TonioOoOo** [NuGet/Home#1823]
Hello,

> In the very nice NuGet 3 Visual Studio 2015 User Interface (thank you for your work), it lacks two very useful things for me and my team:

With 2013 :
1. We have access to **Nuget Gallery via a link** on ID property ;
2. You can **read the release notes** instead of the description (useful especially on the update screen)

![2013nuget](https://cloud.githubusercontent.com/assets/9881996/11711129/8f045c88-9f24-11e5-8c39-32ba1829ab18.PNG)

Same screen in 2015 :
![2015nuget](https://cloud.githubusercontent.com/assets/9881996/11711130/8f1eb74a-9f24-11e5-87a2-440a8d2d60f7.png)

*maintainer edit*

- Pack side - https://github.com/NuGet/Home/issues/1203

**Comment by TonioOoOo** [comment]
Thx !
I think description is needed on Browse/Install screen and release notes on update screen only...

**Comment by xavierdecoster** [comment]
I think the link formats need to be configurable through service document at https://api.nuget.org/v3/index.json (similar to ReportAbuseUrl, the server should be able to declare this feature, client can fallback to nuget.org default)

**Comment by eeinworks8** [comment]
I see the clickable link issue was tagged, but is there any plan to add Release Notes back into VS 2015???

**Comment by yishaigalatzer** [comment]
We can't reliably add a gallery link - like we discussed this only works for nuget.org (so perhaps if we could identify that a package comes from nuget.org, we can do that, but that is not always clear)

**Comment by themadat** [comment]
Bringing back Release Notes would be VERY USEFUL. I would like to see what I am potentially doing when upgrading without have to go out to our repository and search each package I want to upgrade

**Comment by rohit21agrawal** [comment]
@yishaigalatzer @harikm86 

Where should the release notes be placed? (A UI Mockup might be helpful here?)

And what's the final decision on the gallery link?

**Comment by yishaigalatzer** [comment]
We should add a gallery link

Sent from Outlook Mobilehttps://aka.ms/xp9y6l

On Fri, Apr 29, 2016 at 4:59 PM -0700, "Rohit Agrawal" <notifications@github.com<mailto:notifications@github.com>> wrote:

@yishaigalatzerhttps://github.com/yishaigalatzer @harikm86https://github.com/harikm86

Where should the release notes be placed? (A UI Mockup might be helpful here?)

And what's the final decision on the gallery link?

##

**Comment by harikmenon** [comment]
@yishaigalatzer @rohit21agrawal lets chat in the office on Monday. I have a couple of questions I want to clarify before we make this change.

**Comment by rohit21agrawal** [comment]
@yishaigalatzer @rrelyea @harikm86 

I've got this feature working with V2 feeds(snapshot attached below). For V3 feeds, we need the server to send the galleryUrl and releaseNotes in the json. 

![capture](https://cloud.githubusercontent.com/assets/1857490/15000185/b0c8f686-1142-11e6-934f-103afa0b2f37.PNG)

**Comment by Dalmirog-zz** [comment]
Hi Nuget Team. Are there any updates on bringing back the Release Notes for V3?

**Comment by fernandobeltranjsc** [comment]
Bringing back Release Notes would be VERY USEFUL for us!  Any update?

**Comment by yishaigalatzer** [comment]
It is currently slated to 3.6 RC (look at the milestone tab). RC should coincide with VS15 RC release time.

Reality check: Given that we have a long list of issues to resolve for 3.6RC, this item is at a moderate risk of not making it.

**Comment by dmitrii-lobanov-1982** [comment]
Having release notes back would be great. Thanks!

**Comment by 304NotModified** [comment]
+1 for bringing back the release notes. I was surprised that it was suddenly removed.

**Comment by rocklan** [comment]
+1 for bringing back the release notes !

**Comment by steven-dawkins** [comment]
+1 for bringing back release notes

**Comment by lonnkvist** [comment]
+1 for bringing back release notes

**Comment by element533** [comment]
I would like to see release notes as well. I use Jenkins to generate release notes for my packages from Jira issues linked to a given release. Letting other engineers see them would improve adoption of new versions of my libraries.

**Comment by 304NotModified** [comment]
We stopped with a Changelog in the nuspec because of this missing feature.

**Comment by mikek65** [comment]
Is this feature ever going to make it in?

**Comment by thashepherd** [comment]
Please re-add this feature! It's a huge boost to dev quality of life in our workflow.

**Comment by cvvvlad** [comment]
+1 for bringing back release notes

**Comment by aKzenT** [comment]
Is there any update on this?

**Comment by thashepherd** [comment]
Fantastic to see this prioritized! My chief interest is in regards to https://github.com/OctopusDeploy/Issues/issues/2834; it would be very useful for release note metadata to be accessible to Octopus. The idea is for some extra context to be displayed when selecting package versions from this screen:

![image](https://user-images.githubusercontent.com/711467/30070207-b619b3f8-9230-11e7-9e3c-febbb36c4888.png)

Releases notes were displayed here before Octopus updated to 3.5+ internally, and it'd be great to have them back!

**Comment by shahabhijeet** [comment]
Please let me know if this can be prioritized sooner.
We have Azure Cognitive services nuget packages trying to depend upon release notes for their acquisition experience primarily pointing to updates to service samples.

**Comment by rohit21agrawal** [comment]
@shahabhijeet please send email to NuGet team with the business justification

**Comment by KyleInJB** [comment]
+1 for bringing back release notes

**Comment by sungam3r** [comment]
+1

**Comment by gotdablues** [comment]
Are the release notes available in VS 2017 (15.7.3)?  If so, where are they located.

**Comment by sheitmann** [comment]
+1

**Comment by Nehmiabm** [comment]
+1

**Comment by bjuraga** [comment]
Is this still up for grabs? I can contribute some time in adding release notes to the client/s.

**Comment by grigoremircea** [comment]
+1. In our business, we use NuGet packages for dependency management. Our IDE needs to display release notes for each package in order for users to know if they should upgrade to a certain version or not. Right now, users have to go through unnecessary steps to read and understand release notes. Would be very helpful to bring these back.

**Comment by tomarikawa** [comment]
+1 very important feature

**Comment by bjuraga** [comment]
I am looking into how to build the solution and generate a VSIX i found this article: 
https://github.com/NuGet/Home/wiki/Setting-up-the-NuGet-Development-Environment

It seems outdated and not relevant, as well as the Readme file here and on the Home repository.

If i install the generated VSIX from the dev branch to my VS2017 the NuGet Client breaks due to missing **Microsoft.VisualStudio.ComponentModelHost, Version=16.0.0.0**. 

Any help to get the built Client to work in VS2017 is appreciated. I presume there is a branch or tag i should be using instead of the latest on the dev branch?

I already managed to track down and update all the places where release notes need to be added, **just for my curiosity** and would like to test my changes.

**Comment by VivaLaPanda** [comment]
+1 if I'm maintaining a package and release an update, I want users to have an easy way to see whether they should update. This seems like a basic feature and a really simple change.

**Comment by HaGGi13** [comment]
Well this ticket was created before nearly 4 years, is there some information when the issue will be fixed?

In my opinion it is a major feature to provide update information about a new package version.

Currently Visual Studio 2017 displays no release notes for package updates. Can somebody confirm that behavior too?

**Comment by ChristopherTheunissen** [comment]
Not even Visual Studio 2019 16.3.7 displays them.

**Comment by michal-ciechan** [comment]
Still not shown.... :(

**Comment by nkolev92** [comment]
Fixing up the issue title as the gallery link part has been fixed: https://github.com/NuGet/Home/issues/5299.

cc @anangaur This requires server work in addition to client work. 
Open an issue on the gallery to make the server side change: https://github.com/NuGet/NuGetGallery/issues/7956

**Comment by marcselis** [comment]
+1

**Comment by oiBio** [comment]
I hope this will be in Visual Studio 2022 !

**Comment by CamiloTerevinto** [comment]
Six years, multiple iterations of VS (2015, 2017, 2019, 2022), and we still don't have release notes! 

Why is this taking so long? It's just another field for the NuGet Package Manager UI

**Comment by sungam3r** [comment]
😢 Sometimes the best way out will be to accept the reality of what it is.

**Comment by bjuraga** [comment]
Or close this as "won't fix" instead of dragging it out?

**Comment by sonnypdx** [comment]
Please implement this, it is a big time sink to chase the release history.  +1 for bringing back the release notes.  I am in VS2019 and I do not see it whether I open the package manger for either at project level or solution level.

**Comment by renjurajt** [comment]
+1

**Comment by Matze693** [comment]
+1

**Comment by jl-mobitech** [comment]
+1 bump

**Comment by simon-jefferies** [comment]
+1 bump

**Comment by RevZero** [comment]
> TonioOoOo opened this issue on Dec 10, 2015

# 2015

**Comment by Nikita-T86** [comment]
+1 bump

**Comment by tomarikawa** [comment]
+1

**Comment by niprst** [comment]
This deserves an update, it is such a basic feature ?! 
@anangaur any information ?

**Comment by artur-jtw** [comment]
+1

**Comment by stefanluchian** [comment]
Dear Microsoft-Team, can you please implement it or at least tell us what plans do you have regarding this feature?
After 9 years of waiting, I think we - as paying customers - deserve some feedback from you.

**Comment by Ozzian** [comment]
I was also wondering this morning why our internal release notes are not visible in the Package Manager UI - and found myself here. I don't know should I either laugh or cry. Just a simple thing to add into the UI. Now I need to go to the repository and review the release notes from there.

Please fix.

**Comment by BenKmann** [comment]
![grafik](https://github.com/NuGet/Home/assets/12639595/0e709ce7-8704-4a04-8bed-647270aeca16)
Even though the Visual Studio 2022 Project Properties explain the Release Notes property, it should be visible in the Package Manager. However, this is still not the case. Please fix this issue or remove the Release Notes property. Maybe to the 10 Year Anniversary?

**Comment by matt1munich** [comment]
Coming up on TEN YEARS for this open issue.... 🤦🏻‍♂️

![Image](https://github.com/user-attachments/assets/e30fafbc-e7a0-405e-9252-6057fa38a06b)

https://learn.microsoft.com/en-us/nuget/reference/nuspec#releasenotes

**Comment by sjrawlins** [comment]
Yes, please explain (Microsoft): why have a tag called **PackageReleaseNotes** if it doesn't display anywhere?  I fell for it.  Where does it appear? I was expecting to see my "Release Note" appear in VS 2022 Package Manager, but it does not.  Now I am sad.

Here is a subset of my csproj.  I have put my RELEASE NOTES in my README, which maybe is a better approach (more room for history to build), but am curious as to the intended design and use of the csproj tag.

```
   <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Provides enlightenment. </Description>
    <Title>Nirvana</Title>
    <PackageProjectUrl>https://bitbucket.org/nirvana</PackageProjectUrl>
    <Copyright>© Nirvana Enterprises 2025.  All Rights Reserved.</Copyright>
	<PackageReleaseNotes>Improved stuff, but nobody will appreciate this note</PackageReleaseNotes>
  </PropertyGroup>
```

**Comment by sungam3r** [comment]
10 years anniversary

**Comment by TonioOoOo** [comment]
> 10 years anniversary

Priority:2 not 1 ^^ At the time I hadn't managed to do a PR on the project, that might have helped :)

**Comment by SeanFeldman** [comment]
Shoot, I missed to congratulate on the 11th year.

Jokes aside, this is needed. Seeing the release notes for a newly appearing dependency _before_ installing it, or saving the clicks and energy to interrogate nuget.org, would be time-saving. @xavierdecoster, I don't know if you're still around (MSFT, hopefully you're in good health otherwise), or @nkolev92, would it be possible to update the status? Thank you.
