### ISSUE TITLE
Visual Studio restore for project.json is slower in 3.4.2 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2514]
Restore in Visual Studio for Roslyn has gone from 143s to 166s when all caches have been cleared.

**Comment by wgtmpeters** [comment]
It seems to be quit a bit slower , Visual Studio even seems to freeze for a while when restoring.
Did not notice this in version 3.3.x.

**Comment by rrelyea** [comment]
My guess is that your current batch work may address this. However, you likely need to be able to support batch at one level higher. let's chat.

**Comment by drewgillies** [comment]
Looks like this is more than fixed by https://github.com/NuGet/NuGet.Client/commit/3b6f15a17a681dd4c5acc36fe5db2b13d9b058e0 -- I've seen roughly an 80% drop in time to restore Roslyn within VS.

**Comment by rrelyea** [comment]
Awesome!

**Comment by drewgillies** [comment]
Will keep this open until I successfully cherry-pick the change across to release-3.4.5

**Comment by emgarten** [comment]
That sounds like a great perf improvement. From my traces I saw downloads taking longer in 3.4.0 than 3.3.0, I think there is still an issue there. The largest change in that area was to add support for download timeouts which works by starting multiple tasks for each chunk of the download. A local server will be needed to fully verify the download perf, I wasn't able to get consistent results from nuget.org.

**Comment by drewgillies** [comment]
https://github.com/NuGet/NuGet.Client/commit/d05cddb219921b5e5fe73490f93c9d357779af4b
Cherry-picked into release-3.4.5. Closing.
The chunking work sounds good--perhaps we can track this in a non-3.4.5 issue as lower-pri.

**Comment by rrelyea** [comment]
we reverted the earlier batch fix for project.json. reopening.
