### ISSUE TITLE
NuGet doesn't install dependencies for default group

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#3000]
With a PCL 259 project, installing a package that has both some dependencies in groups with target frameworks and some with a default, NuGet does not apply the default group.

This is with NuGet 3.5.0.1502 and VS 2015 Update 3 RC.
Note: this also repro's with 3.4.4.1321 (latest on the VS Gallery).

Repro is here:
https://github.com/Reactive-Extensions/Rx.NET/tree/integration-tests/Rx.NET/Integration/Pcl259

Tried to install the `System.Reactive` package, which is a meta-package that has the following metadata: https://github.com/Reactive-Extensions/Rx.NET/blob/integration-tests/Rx.NET/Source/NuSpecs/System.Reactive.nuspec#L17-L47

On a PCL 259, you can see that it didn't resolve any of the four dependencies in the default group:
https://github.com/Reactive-Extensions/Rx.NET/blob/integration-tests/Rx.NET/Source/NuSpecs/System.Reactive.nuspec#L18-L23

A netstandard1.0 xproj/project.json library did work and resolved dependencies correctly.

iOS didn't install correctly either. Seems like `packages.config` based projects aren't picking up the default dependency group.

**Comment by emgarten** [comment]
This appears to be a MyGet issue. Copying System.Reactive to a local folder and installing from there works correctly for me.

In the NuGet package manager UI the group without a target framework attribute should display as _Any_, but instead it shows up as _Unsupported_. This is coming from the MyGet feed and is causing that group to be ignored.

Snippet from https://www.myget.org/F/rxnet/api/v3/registration1/system.reactive/index.json

``` json
{
  "dependencyGroups": [
  {
    "@id": "https://www.myget.org/F/rxnet/api/v3/registration1/system.reactive/3.0.0-rc1-00346.json#dependencygroup/unsupported0.0",
    "@type": "PackageDependencyGroup",
    "targetFramework": "Unsupported0.0"
  }
  ]
}
```

Changing to the V2 myget feed didn't seem to help, both v2 and v3 seem to this issue.

For xproj/project.json NuGet downloads the nupkg directly and then reads the nuspec instead of going by the feed which is why it works there.

//cc @xavierdecoster @maartenba

**Comment by maartenba** [comment]
@emgarten We are using NuGet.\* 3.5.0-beta2-1437. Looks like there is an inconsistency in there.

When parsing the metadata using `ManifestReader`, we actually get back `Unsupported`:

![1](https://cloud.githubusercontent.com/assets/485230/16184834/b2060a50-36bf-11e6-98ea-08600f787767.png)

When using `PackageArchiveReader`'s `GetPackageDependencies()`, we get back `Any`:

![2](https://cloud.githubusercontent.com/assets/485230/16184837/b5e55446-36bf-11e6-86e8-5a59cc14d0e7.png)

A deployment has been done switching to `GetpackageDependencies()`.

@onovotny we re-processed the packages on your feed so that the dependencies are now correct. And on a side note, this feed may be good to have on https://dotnet.myget.org instead?

**Comment by clairernovotny** [comment]
@xavierdecoster Just re-checked my repro and it seems resolved now, thanks! Happy to move the feed over to https://dotnet.myget.org, just curious though what the advantages are? Can the feed be moved or do I need to create a new one there? Let's connect offline to get this done.

**Comment by emgarten** [comment]
@maartenba I suggest using `NuspecReader`. `ManifestReader` was porter over just for the pack command and is only used there, it looks like some work still needs to happen there along with comments on why it still exists in the new library.

**Comment by maartenba** [comment]
Thanks @emgarten!
