### ISSUE TITLE
Error "could not be found in your workspace, or you do not have permission to access it"

### ISSUE THREAD

**Issue by CobraCalle** [NuGet/Home#3353]
I know, there were many issues about this and all of those issues where closed / fixed. But the problem is still alive... nothing changed for me.

In the past we could help us by using Visual Studio 2013, but now we have some project types that are nor compativle with visual studio 2013, so we are stucked and have to update the nuget-references BY HAND!!!!

So please, have a look at this. This is a VERY BIG problem. Because it is simply not possible to update nuget references when your solution ist tfs controlled.

And the worst: When it failed to add the new nuget, it removes the reference to the old version and removes to entry in packages.config... so the whole solution is corrupted after you try to update.

**Comment by CobraCalle** [comment]
OK... the problem is not related to TFS... creating a complete new project and adding a reference from our lokal repository don't work to.

Attempting to gather dependency information for package 'Diomex.Framework.Release.2.1.16236.1' with respect to project 'PackagesConverter', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 677,81 ms
Attempting to resolve dependencies for package 'Diomex.Framework.Release.2.1.16236.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Diomex.Framework.Release.2.1.16236.1'
Resolved actions to install package 'Diomex.Framework.Release.2.1.16236.1'
Retrieving package 'Diomex.Framework.Release 2.1.16236.1' from 'Diomex'.
Adding package 'Diomex.Framework.Release.2.1.16236.1' to folder 'c:\users\c.bickmeier.diomex\documents\visual studio 2015\Projects\PackagesConverter\packages'
Added package 'Diomex.Framework.Release.2.1.16236.1' to folder 'c:\users\c.bickmeier.diomex\documents\visual studio 2015\Projects\PackagesConverter\packages'
Install failed. Rolling back...
Package 'Diomex.Framework.Release.2.1.16236.1' does not exist in project 'PackagesConverter'
Removing package 'Diomex.Framework.Release.2.1.16236.1' from folder 'c:\users\c.bickmeier.diomex\documents\visual studio 2015\Projects\PackagesConverter\packages'
Removed package 'Diomex.Framework.Release.2.1.16236.1' from folder 'c:\users\c.bickmeier.diomex\documents\visual studio 2015\Projects\PackagesConverter\packages'
Executing nuget actions took 1,7 sec
Failed to add reference to 'Diomex.Framework'.
========== Finished ==========
Time Elapsed: 00:00:03.0056608

**Comment by rrelyea** [comment]
1) unsure how to repro this, since this package seems internal. Can you share this package with us via email to support@nuget.org?
or
2) perhaps we have fixed this in our latest work. Version 3.5.0-rc1 is available for download from http://nuget.org/downloads

**Comment by josh-sachs** [comment]
Reproduce it by actually trying to get work done on a TS project in VS2015 update 3... In all seriousness, this is an issue in 2015 too.  We are using TFS through visualstudio online.  It seems to crop up after doing a clean on a mixed typescript/.cs project.  Every time I save a file, I get the error now.  It is ocassionaly accompanied by a TFS dialog that says "undoing pending changes" and has me staring at the screen for a few minutes.

**Comment by mangeshdurge** [comment]
I am getting same issue in VS2015

**Comment by A87P** [comment]
I'm getting the same issue dealing with TypeScript. 

It also gives me a nice red error message with a title "Check Out" and a body "presentation\app.js could not be found in your workspace, or you do not have permission to access it."

I bet it's VS generic issue and has nothing to do with NuGet. I tried to turn off plugins that I thought may have tried to access the file too, but it still failed to checkout. And once I got that message, manual check out stops working too and gives the same message too.

**Comment by palikhe** [comment]
I'm same same issues with .edmx file and Context.tt . I had some major changes in the database and after this everytime i rebuild am getting file could not be found in your work-space or you don't have permission to access it.

**Comment by Navidsoft** [comment]
I fixed the error.
I was simple.
just Check in the latest changes in project , OR get the latest changes and synchronize both tfs and local code.
then you will see every thing is OK.

**Comment by ZeeshanAhmadKhalil** [comment]
Getting the same issue while adding edmx file in VS2019 MVC project. I think everyone should stop using dead .net technologies and switch to NodeJS technologies.
