### ISSUE TITLE
Can't enable package source from local config if that source is disabled in global config.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3608]
@skofman1 found this issue (happens on 3.5-rtm, 3.6-beta1, dev)
Repro Step:
local config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

Global config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
   <disabledPackageSources>
      <add key="dotnet-core" value="true" />
   </disabledPackageSources>
</configuration>
```
1. Open setting UI and enable package source dotnet-core.
2. click OK.

Expect: dotnet-core source is enabled.
actual: dotnet-core source is still disabled.

the issue is from here : https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L391-L394

removing this part will make it work.

This is not a regression from 3.4.4 but it's still pretty bad.

**Comment by zhili1208** [comment]
@rrelyea @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Seems like a super edge case for me. The user cannot get into this case from the UI, it can wait

**Comment by jainaashish** [comment]
Looks like a edge case and no customer report so far. So closing it for now.

**Comment by sharwell** [comment]
@jainaashish I hit this today and lost more than an hour having no idea what/how/why it happened.

Steps to reproduce:

1. In Visual Studio 15.8 Preview 2 Tools &rarr; Options, create a package source with the name **api.nuget.org**
2. Disable the package source
3. Close Visual Studio
4. Open a solution which contains a **NuGet.Config** file that defines **api.nuget.org** as a source, such as [this one](https://github.com/aws/aws-sdk-net/blob/fa0899fe3f9a9009e48b40b3431e6918390b87af/sdk/NuGet.Config)
5. Close the solution
6. Open Tools &rarr; Options
7. Remove the package source **api.nuget.org**
8. Close Visual Studio
9. Open the solution from step 4

Under these steps, there is no way to enable NuGet for the solution and everything fails.

**Comment by jainaashish** [comment]
@sharwell I still feel it's super edge case because I haven't seen many cases where users have explicitly define `nuget.org` source (with a different name than already present in global nuget.config file), then disable it for a solution, and then add again to another solution, etc.. 

@rrelyea @anangaur to take a call if we should fix it. Although fix seems simple but not sure about the consequences.

**Comment by sharwell** [comment]
@jainaashish The fix seems easy. When I removed the source, it should have removed the key from both `packageSources` and `disabledPackageSources`, but it only actually removed it from the former.

**Comment by dynamictulip** [comment]
I also hit this issue today

> /cc @yishaigalatzer I hit this by accident from the UI and had no idea what to do

**Comment by jveselka** [comment]
I can confirm the issue still exists. Hit it today also from the UI.
