### ISSUE TITLE
Create website use server HTTP or FTP, PMC Show error in output window - not a regression

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4224]
please investigate internal bug 297509
(also collect info - is this a new issue with VS2017 or did it happened in VS2015?)

**Comment by zhili1208** [comment]
the problem is 
the package Microsoft.Web.Infrastructure.1.0.0.0 from C:\Program Files (x86)\Microsoft Web Tools\Packages\
Contains Install.ps1 which try to access "NuGet.VisualStudio.ISolutionManager" in tools folder. 

"NuGet.VisualStudio.ISolutionManager" is a nuget 2.x API, it no longer exist in nuget 4.x

Also check the same package from nuget.org. It only contains lib folder and no tools folder.

I think we should fix this package

**Comment by zhili1208** [comment]
validated it with VS 26205 and nugget 4.0.0.2275

**Comment by zhili1208** [comment]
VS.psm1 still contains 2.x API

**Comment by rrelyea** [comment]
NuGet.Core.dll has been removed from VSIX. Determine compat risk in PS1 files.

**Comment by mishra14** [comment]
I tried the scenario on VS 2015 Update 3 + NuGet 3.4.4 - Still Get the same errors - 

![capture](https://cloud.githubusercontent.com/assets/10507120/22811182/2933a0c0-eef2-11e6-9d4f-49547b53aad5.PNG)



I am trying to get a repro on VS2015 RTM + NuGet 3.0.0

**Comment by mishra14** [comment]
This repros on NuGet 3.0.0 on VS2015 RTM as well.

![capture2](https://cloud.githubusercontent.com/assets/10507120/22839054/a448a9e2-ef7c-11e6-8558-5f20719dc9e4.PNG)
