### ISSUE TITLE
allow dotnet pack to pack nuspec file without needing a csproj file

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4254]
Follow up to https://github.com/NuGet/Home/issues/3904#issuecomment-267671637

Scenario:
I want to pack a nuspec file in an x-plat build system.

Inputs: 
- nuspec
- files

NB: I am not packing a csproj, just files.

In <= 4.0.0-rc2, this was available as `dotnet nuget pack (nuspec)` file. This was removed in 4.0.0-rc3 https://github.com/NuGet/NuGet.Client/pull/1065 without a suitable replacement.

More data to consider:

- This is is a common scenario for the ASP.NET Core runtime team.
- Although possible to use nuget.exe, this requires running 'mono nuget.exe' on xplat, which is less than ideal, not to mention buggy.

cc @emgarten @rohit21agrawal 

Please 👍 or 👎 this comment to help us with the direction of this feature & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

Thank You 🎉

**Comment by rohit21agrawal** [comment]
closing this as a duplicate of  : https://github.com/NuGet/Home/issues/4250

**Comment by natemcmaster** [comment]
I don't think these are duplicates. #4250 is about issues packing with csproj + nuspec. This one is about packing nuspec **without** a csproj file.

**Comment by rohit21agrawal** [comment]
aah i see, i don't think this will  be accommodated in 4.0-RTM as you need a way of getting the Pack targets imported so dotnet pack can work properly - which is why we have a requirement of having a dummy csproj right now

**Comment by enricosada** [comment]
Same issue there. But if possibile can be done like csproj instead of nuspec? One thing less to learn.

For me is not an issue use a csproj instead of nuspec who can `dotnet pack`, but without doing AND requing the build.
If i use `--no-build` the `dotnet pack` anyway expect the built assemblies so fail.

Maybe we can use the csproj, but the `dotnet pack --no-build --no-assemblies` who doesnt build and doesnt expect built assemblies. 
A property inside csproj is ok too `<PackageNoAssemblies>true</PackageNoAssemblies>` to configure that.

**Comment by rohit21agrawal** [comment]
@enricosada you can use ```<IncludeBuildOutput>false</IncludeBuildOutput> ``` to achieve the same.

**Comment by rohit21agrawal** [comment]
To see a list of all possible scenarios in dotnet pack, refer to  : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

**Comment by natemcmaster** [comment]
For a little more context: the scenario I have in mind is that we produce some custom nuget packages with  layouts that are hard to achieve using csproj, or even some packages that don't come from a .NET project at all.

Example: https://github.com/natemcmaster/libsqlite3-package/blob/ba16e2ede7768cf80cfe7a6023109e2c5a59e30e/SQLite.nuspec

**Comment by enricosada** [comment]
@natemcmaster using a csproj like

```xml
    <Content Include="files/SQLite.props">
      <PackagePath>build\net45\</PackagePath>
      <Pack>true</Pack>
    </Content>
```

doesnt work? i can set `<PackagePath>` to specify any directory inside package

**Comment by natemcmaster** [comment]
Yes, that would work for that specific example, but why should I need a csproj when I'm just packing things? I'm not compiling C#.

**Comment by rohit21agrawal** [comment]
You need a way to import the pack targets, and that is being achieved by having a csproj that does that for you.

**Comment by enricosada** [comment]
@natemcmaster 
- `dotnet pack --no-build` doesnt compile
- one sintax to lean, the msbuild based csproj/fsproj (used often i think if dotnet pack works) instead of the nuspec

**Comment by enricosada** [comment]
thx @rohit21agrawal works, using

```xml
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
```
and
```
dotnet restore
dotnet pack --no-build
```

generate the nuspec, with no compile and no dependencies (i dont need these)
the `dotnet restore` is unfortunate, but better than nothing atm

**Comment by karajas** [comment]
Just wanted to follow up in this thread, I too would like a way to pass in the nuspec directly with the option to pass in command line nuspec properties. Is something like this in the pipeline?
```
dotnet pack /p:NuspecFile=myproject.nuspec /p:NuspecProperties=""
```
Could a default pack.targets file be imported if a nuspec file is passed on the command line? This would ensure that the right targets would be imported in the case of both csproj and nuspec files.

**Comment by anangaur** [comment]
We should allow `dotnet pack` with nuspec files. Currently this is a major dissatisfaction for pack on Linux and non Windows platforms. 
I think the following option would be better:
```
> dotnet pack <project> --nuspec-file=myproject.nuspec 
```

**Comment by rohit21agrawal** [comment]
you need a project that would import the targets that define the pack task. it's not as straightforward.

**Comment by natemcmaster** [comment]
> > dotnet pack <project> --nuspec-file=myproject.nuspec 

This still requires an MSBuild project, right? What I'm asking for is the ability to pack a nuspec **without** any MSBuild project file at all. Conceptually, this as a new dotnet gesture:

```
dotnet pack-nuspec MyPackage.nuspec
```

As an implementation detail, you could put this in `dotnet-pack`, or `dotnet-nuget`, but that piece is less important to me than the ability to pack without a \*.csproj file.

**Comment by anangaur** [comment]
@rohit21agrawal I did not fully get what you meant here. Why shouldn't it just do what `nuget pack` does? Assuming everything is in place including the nuspec file.

@natemcmaster Agree.

For end user its confusing if there are two implementations of pack available under 2 different options. i.e. there shouldn't be `dotnet pack` as well as `dotnet nuget pack` both having different behavior.

**Comment by natemcmaster** [comment]
> For end user its confusing if there are two implementations of pack available under 2 different options.

I know `nuget.exe pack` combines packing csproj and nuspec into one command. I don't know what kind of feedback you've had on this. My uninformed point-of-view is that having two modes of dotnet-pack can be just as confusing. There are command line options on dotnet-pack today that wouldn't apply if you were calling `dotnet pack MyPackage.nuspec`. For example, `dotnet pack MyPackage.nuspec --no-restore --runtime win7-x64`...what would those parameters mean in a nuspec-only pack context? The reverse would be true if you added options to dotnet pack that only apply when packing a nuspec file directly, but don't apply to csproj.

**Comment by anangaur** [comment]
I think we are on the same page. May be my wordings were ambiguous. I am against having another command `dotnet nuget pack`. I would rather have `dotnet pack --nuspec-file mypackage.nuspec` or just `dotnet pack mypackage.nuspec`.

**Comment by natemcmaster** [comment]
Thanks for clarifying. Yes, something like `dotnet pack --nuspec-file mypackage.nuspec` is the ask here.

I was just trying to point out that there may be a problem with command-line options that only apply to csproj or nuspec packing, but not both.

**Comment by anangaur** [comment]
We also need token replacement functionality in dotnet that exists today with nuget.exe.  Typically I would want to use the version information from the assembly metadata to use as the package version (is this broken? https://github.com/NuGet/Home/issues/5807)

**Comment by JamieKeeling** [comment]
This is certainly something I would love to see happen.

I am leveraging the new templating functionality in the .NET CLI and I would like to make use of Nuget as a distribution vector instead of raw files.

The [documentation](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#use-nuget-distribution) states that you only need a .nuspec file and to then invoke `nuget pack`, but as @natemcmaster mentioned that involves using the mono equivalent for xplat.

Looking at the docs for [dotnet pack](https://docs.microsoft.com/en-us/nuget/tools/dotnet-commands) it states

> Packs the code into a NuGet package. As of NuGet 4.0, this runs the same code as nuget pack.

This implies that the documentation is incorrect as it doesn't operate on a like for like basis, nuget v4.4.1 allows the .nuspec only howevrer the nuget implementation bundled in with v2.0.3 of the .NET Core CLI does not.

**Comment by rohit21agrawal** [comment]
@JamiKeeling The documentation is indeed incorrect . Thanks for reporting that, I already have sent a PR to fix it.

We have taken your feedback into consideration, will keep you updated on progress

**Comment by tannergooding** [comment]
FYI. @jaredpar

**Comment by jaredpar** [comment]
As someone who just ran into this, have to say this is a major pain point in taking our repository cross platform. We have ~30 packages that are all driven by using `nuget pack nuspec`. Moving to `dotnet pack` is a non-trivial operation and when complete will be demonstrably slower than the old infrastructure. 

In particular it's non-trivial because there is no comprehensive documentation available on how to approach this. There are a scattering of issues on GitHub but none that have a comprehensive solution.

**Comment by rohit21agrawal** [comment]
@jaredpar the documentation is here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec 

Can i ask what were the issues you encountered when trying to pack using csproj + nuspec? You mentioned you actually were happy with the ability of being able to pass the nuspec file as a property through csproj.

**Comment by natemcmaster** [comment]
The point of this bug is that we often want to pack WITHOUT a .csproj file. Creating a dummy .csproj just so we can invoke pack seems like an additional hoop we shouldn't need to jump through.

By the way, in aspnet we decided to workaround this by creating an xplat tool to pack a nuspec directly. https://github.com/aspnet/BuildTools/blob/dev/modules/KoreBuild.Tasks/PackNuSpec.cs

**Comment by rohit21agrawal** [comment]
@natemcmaster yes I do understand what the point of the bug is , I am just trying to understand what difficulties @jaredpar faced in particular

**Comment by jaredpar** [comment]
@rohit21agrawal 

That documentation is incomplete. Areas it does not cover:

1. How do I avoid doing a build every time I pack? Or avoid builds at all. Can't see any good justification for having a new DLL in my output just so I can zip up my NuPkg. 
1. How should I handle the case where my NuSpec file has no relation to any single project in my tree? Think of tools which can't be expressed as a csproj but rather are defined by a Nuspec that grabs from various output directories. 
1. Given the case where I have to define an unused csproj what TF should it use? Must it be an SDK project? Is there a template somewhere I can draw from? 

The second concern is probably the greatest. There are many nuspec files we have which don't have a project associated with them. Now though I have to create a project, restore and build it even though it's just an empty DLL that will never be shipped, tested or used in any way. 

> You mentioned you actually were happy with the ability of being able to pass the nuspec file as a property through csproj.

That's a bit misleading. My ideal case is `dotnet pack blah.nuspec` but that's not possible. I must have a csproj file. But once I'm forced into having a csproj file it's nice that I can define a smaller number and control the nuspec file they use with a parameter.

**Comment by dasMulli** [comment]
> How do I avoid doing a build every time I pack? Or avoid builds at all.

This has come up before on the SDK repo not only for packing a NuSpec, but for creating "meta-packages" that don't have build output but only package references.

Since MSBuild 15.6 introduced a NuGet SDK resolver and https://github.com/Microsoft/MSBuildSdks contain SDKs for projects without assemblies (`NoTargets` and `Traversal`), they could maybe be extended with NuGet support so that project-file-integrated NuGet will work but won't see any assembly build output

**Comment by rohit21agrawal** [comment]
@jaredpar for now I have updated the docs to suggest a way of not building when using a nuspec to pack. ( https://github.com/NuGet/docs.microsoft.com-nuget/pull/755 ) and your question in 3) about what kind of project file and TF to use in the dummy csproj.

**Comment by jaredpar** [comment]
@rohit21agrawal commented on your updated docs. They are incorrect. There is no way I can find to avoid at least restoring the project. 

Here are the files I'm using for context:

example.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <NuspecFile>example.nuspec</NuspecFile>
  </PropertyGroup>
</Project>
```

example.nuspec
``` xml 
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Microsoft.Net.Compilers</id>
    <summary> .NET Compilers package.  </summary>
    </description>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <version>1.0.0</version>
    <authors>Microsoft</authors>
    <licenseUrl>https://blah.com</licenseUrl>
    <projectUrl>https://blah.com</projectUrl>
    <tags></tags>
  </metadata>
  <files>
  </files>
</package>
```

The command lines I've tried:

```
> dotnet pack --no-build example.csproj
C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Assets file 'C:\Users\jaredpar\temp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\jaredpar\temp\example.csproj]
C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\Users\jaredpar\temp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\jaredpar\temp\example.csproj]

> dotnet restore example.csproj

C:\Users\jaredpar\temp> dotnet pack --no-build .\example.csproj
Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Assets file 'C:\Users\jaredpar\temp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\jaredpar\temp\example.csproj]
C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\Users\jaredpar\temp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\jaredpar\temp\example.csproj]
C:\Users\jaredpar\temp> dotnet restore .\example.csproj
  Restoring packages for C:\Users\jaredpar\temp\example.csproj...
  Generating MSBuild file C:\Users\jaredpar\temp\obj\example.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\jaredpar\temp\obj\example.csproj.nuget.g.targets.
  Restore completed in 272.88 ms for C:\Users\jaredpar\temp\example.csproj.
> dotnet pack --no-build .\example.csproj
Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): error : The file 'C:\Users\jaredpar\temp\bin\Debug\netcoreapp2.0\example.dll' to be packed was not found on disk. [C:\Users\jaredpar\temp\example.csproj]
```

This is basically where I spent hours of my life last night. The docs are incomplete and there is no comprehensive sample that gives you a guide here.

**Comment by rohit21agrawal** [comment]
you are right, I'll send out an update in a bit. Turns out you do need to restore atleast once, and if you don't want to build at all, you also need to pass ``` /p:IncludeBuildOutput=false ```

**Comment by jaredpar** [comment]
@rohit21agrawal thanks for updating the docs. 

Overall though this still seems like a less than ideal situation. Have to add and restore a project that has zero functioning code just to continue using our nuspec files cross platform or adopt the CLI.

**Comment by brazilbean** [comment]
We would also love to see this feature addressed. We often pack things that are are not associated with a project and creating wrapper project just to reference the nuspec file (while ensuring the proper incantation of tags is specified: no build, no build output, etc.) is very cumbersome.

Is there any ETA on this feature? If we knew this would be addressed in the near future (or not if that's the case) it would help us in some current decision making.

**Comment by jaredpar** [comment]
@rohit21agrawal when I use `/p:IncludeBuildOutput=false` the pack project still builds.

**Comment by rohit21agrawal** [comment]
right, I meant to say ``` NoBuild```

**Comment by JamieKeeling** [comment]
Are we any further in resolving the initial issue whereby you're forced to use a .csproj?

I need this as a Nuget package so I can distribute it easily.

**Comment by JamieKeeling** [comment]
It's looking like I have no choice but to use a dummy .CSPROJ to get this up and running.

Could somebody provide an example of the bare minimum content for a valid CSPROJ file?

**Comment by jaurenq** [comment]
Just wanted to point out here that project templates for use with "dotnet new" are a use case for this.  If you follow the instructions here...

https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template

...they mostly make use of the dotnet cli, but the template is packaged up for nuget **as content**, rather than being built to **create content**, and the instructions to do that are to make a .nuspec file and then use 'nuget pack'.  It's the only place nuget.exe is used in that workflow; the other steps all use dotnet.exe.

It's a pain point for me b/c it's the only reason I need a command-line nuget to be available to build my project xplat -- I can use the dotnet cli for everything else -- which means I can't just tell users "Get the .NET Core 2.x SDK and it'll 'just work'".

**Comment by klemmchr** [comment]
Is there any progress about this issue? Needing to pack dotnet templates with nuget cli or with a dummy project is a PITA.

**Comment by geekyed** [comment]
> Is there any progress about this issue? Needing to pack dotnet templates with nuget cli or with a dummy project is a PITA.

Do you have a workaround for templating, I am really struggling to get anything together.

**Comment by klemmchr** [comment]
> Do you have a workaround for templating, I am really struggling to get anything together.

My current solution is a dummy project that contains a reference to my nuspec file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <NuspecFile>Sample.nuspec</NuspecFile>
  </PropertyGroup>
</Project>
```
My nuspec:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Sample</id>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
  </metadata>
  <files>
    <file src="content/**" target="" />
  </files>
</package>
```
My templates are located in the subfolder `content`, each in it's own folder.
The version is missing from the nuspec as I'm setting it while packing:

`dotnet pack Sample.csproj -p:NoBuild=true -p:PackageVersion=1.0.0 -p:NoDefaultExcludes=true -o publish`

Note the different syntax for properties. Normally you would specify them with `/p:Foo=true` however with dotnet pack it's `-p:Foo=true`. The NuGet package will be located in the `publish` folder.
I think you can skip the build with `--no-build` but you have to restore the project at least once to make the publish work. `dotnet pack` is doing that automatically for you unless you specify `--no-restore`.

**Comment by tebeco** [comment]
@chris579 do you end up with the `csproj` and the `obj` folder packaged as well in the nupkg ?
it's kinda anoying ^^

i used somnething similar like :
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>XXXXXX</id>
    <version>XXXXXX</version>
    <title>XXXXXX</title>
    <authors>XXXXXX</authors>
    <owners>XXXXXX</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectUrl>XXXXXX</projectUrl>
    <description>XXXXXX</description>
    <copyright>XXXXXX</copyright>
    <language>en-US</language>
    <tags></tags>

    <packageTypes>
      <packageType name="Template" />
    </packageTypes>

    <references>
      <reference file="foo.dll" />
      <reference file="bar.dll" />
      <reference file="foobar.dll" />
    </references>

    <dependencies exclude="obj">
      <group targetFramework=".NETStandard2.0" />
    </dependencies>

  </metadata>
</package>
```

```
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NuspecFile>Sgme.Ium.UltraMessenger.nuspec</NuspecFile>

    <NoBuild>true</NoBuild>
    <NoRestore>true</NoRestore>
  </PropertyGroup>
</Project>
```

Same if i add `<IncludeBuildOutput>false</IncludeBuildOutput>` to the csproj
or if i run
```
rm -rf bin
rm -rf obj
dotnet pack  /p:IncludeBuildOutput=false
```

**Comment by tebeco** [comment]
@chris579 do you end up with the `csproj` and the `obj` folder packaged as well in the nupkg ?
it's kinda anoying ^^

i used somnething similar like :
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>XXXXXX</id>
    <version>XXXXXX</version>
    <title>XXXXXX</title>
    <authors>XXXXXX</authors>
    <owners>XXXXXX</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectUrl>XXXXXX</projectUrl>
    <description>XXXXXX</description>
    <copyright>XXXXXX</copyright>
    <language>en-US</language>
    <tags></tags>

    <packageTypes>
      <packageType name="Template" />
    </packageTypes>

    <references>
      <reference file="foo.dll" />
      <reference file="bar.dll" />
      <reference file="foobar.dll" />
    </references>

    <dependencies exclude="obj">
      <group targetFramework=".NETStandard2.0" />
    </dependencies>

  </metadata>
</package>
```

```
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NuspecFile>Xxxxxx.nuspec</NuspecFile>

    <NoBuild>true</NoBuild>
    <NoRestore>true</NoRestore>
  </PropertyGroup>
</Project>
```

Same if i add `<IncludeBuildOutput>false</IncludeBuildOutput>` to the csproj
or if i run
```
rm -rf bin
rm -rf obj
dotnet pack  /p:IncludeBuildOutput=false
```

**Comment by Dan-True** [comment]
Any progress on this? We're also keen to pack any sort of files, in a docker container built on linux. I will try the various .csproj workarounds that are being suggested.

**Comment by klemmchr** [comment]
> Any progress on this? We're also keen to pack any sort of files, in a docker container built on linux. I will try the various .csproj workarounds that are being suggested.

It’s already possible. See the [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) for reference. IMO this issue can be closed.

**Comment by tebeco** [comment]
> It’s already possible. See the docs for reference. IMO this issue can be closed.

You might be right here, just point points though:

The docs does not mentions `PublishBuildOutput` as `IncludeBuildOutput` did not worked, especiallly if all you do is posting a link and "It's here, please close"
=> does not always work

Having to guess that the page about `custom-template` would help doing `third part vendor` packaging and `dotnet pack` without packing `dotnet build` output is nearly impossible to guess
=> missleading page
=> probably not the page expected

This issue might be closed if `IncludeBuildOutput` is properly addressed in `dotnet pack` page
This is the real issue here, the docs had information but on pages that you wont take a look at.
IMO we could move details to `dotnet pack` and `custom template` would mention `IncludeBuildOutput` with a link / full explanations to the `dotnet pack` page

The not funny part is that this issue was open a long time ago and last year `~August 2019` even though I looked in many many many places I did not found that out
`git blame` indicate at least `May 2019`
=> knowledge lost by both community and team

And I finally managed to get that working with something else (that might be wrong if I just follow the given page about `custom template` while trying to pack a `third part`):
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PublishBuildOutput>false</PublishBuildOutput> <=============== the docs indicates IncludeBuildOutput, what's the difference with it ? not in that docs page :s
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../binaries/native_one.dll" Pack="True" PackagePath="runtimes/win-x64/native" />
    <None Include="../binaries/native_two.dll" Pack="True" PackagePath="runtimes/win-x64/native" />

    <None Include="../binaries/dotnet/managed_wrapper.dll" Pack="True" PackagePath="runtimes/win-x64/lib/netcoreapp3.1" />
    <None Include="../binaries/dotnet/managed_wrapper.xml" Pack="True" PackagePath="runtimes/win-x64/lib/netcoreapp3.1" />
    </ItemGroup>
</Project>
```

**Comment by dasMulli** [comment]
The issue still is about packing a .nuspec file without any project files. Currently you need a project file that uses the `NuGet.Build.Tasks.Pack` package (either as nuget or via .NET SDK).

So this is issue is more specifically about allowing for `dotnet nuget pack some.nuspec` which does have some advantages over a project file (for example, not needing any restore/build/* semantics) - if you know what you are doing ^^.

**Comment by sayedihashimi** [comment]
I believe that this is important for packing templates in a .nupkg file when running on an OS that is not windows.

**Comment by Steinblock** [comment]
Is there a solution for this?

I have done this to pack external dependencies (which might not necessarily have to be assemblies) into nuget packages.

I have done this for years with `nuget.exe` and the 4.x framework.

Now I need to do the same on a linux based ci server with dotnet core 3.1 (408) and I can't figure out how to do this.

**Comment by zivkan** [comment]
@Steinblock you can create a csproj with no code files, so it's fast to compile, or use the [Microsoft.Build.NoTargets SDK](https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets). Then, set the `NuspecFile` msbuild property to the path & filename of your nuspec file. Packing that project file should work, although I've either never tested it, or it's been such a long time that I don't remember. `NoTargets` does sound a little scary, like maybe it's blocking NuGet's `Pack` target.

**Comment by Steinblock** [comment]
@zivkan 

Thanks. I didn't try `NoTargets` but a simple `csproj` with `<IncludeBuildOutput>false</IncludeBuildOutput>` seems to work.

I even used content files with a custom packagepath so I don't need an additional nuspec file.

This adds some seconds to my CI pipeline because of the build process but it works.

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageVersion>1.0</PackageVersion>
        <PackageId>My.VueApp</PackageId>
        <Title>My VueApp</Title>
        <Authors>me</Authors>
        <Description></Description>
        <PackageTags>my;vue;app</PackageTags>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <IncludeContentInPack>true</IncludeContentInPack>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <ContentTargetFolders>content</ContentTargetFolders>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="dist/*.html">
            <PackagePath>content/public/</PackagePath>
            <Pack>true</Pack>
        </Content>
        <Content Include="dist/**/*">
            <PackagePath>content/public/</PackagePath>
            <Pack>true</Pack>
        </Content>
    </ItemGroup>
</Project>
```

**Comment by patrickklaeren** [comment]
+1 this would be massively beneficial in our scenarios where we need nuget packages to create a Squirrel installer.

**Comment by GreatTeacherBasshead** [comment]
5 years later this is still needed!

**Comment by brat000012001** [comment]
Are there any existing workarounds  than installing mono and nuget,  etc. see https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools?

**Comment by aronweiler** [comment]
Can't believe I'm here 5 years after the initial request to have this supported... why can I not use `dotnet pack` with a `.nuspec` file WITHOUT a `.csproj`?

**Comment by ldennington** [comment]
+1

**Comment by blowdart** [comment]
Adding myself to the +1s 😐

**Comment by FredrikLarssonn** [comment]
+1 We create our own nuspec from a csproj to tell other dependencies and set other dependency versions

**Comment by ghost** [comment]
+1

**Comment by JonDouglas** [comment]
Hi friends,

As you may have seen, we've tagged this issue as a potential item for this year. I know there have been a number of "+1s" and 👍, but we need some more help.

If you can give us a quick comment on how this functionality will help your scenario if it's not already listed(installers, re-packing, templates, wrapper packages, repository migration from nuget.exe to dotnet CLI, etc) that would be especially helpful. The more the merrier.

**Comment by Nirmal4G** [comment]
You don't need to have a project file to pack MSBuild SDK and Extension packages if they don't need to have compiled code. Having project files in this scenario just complicates things...!

**Comment by Nitschi** [comment]
This would help us in 3 ways:
- Allows the chocolatey team to get rid of the mono/nuget dependency and move to dotnet core => Allow packaging chocolatey packages on Linux
- Or it allows us to do that directly without waiting for the chocolatey team to implement this

Non-choco:
- Allow for simple csproj files for development and use NUKE to worry about what should and what shouldn't be packed inside the .nupkg

**Comment by gao-artur** [comment]
We are distributing `proto` files with nuget as described [here](https://stackoverflow.com/questions/66844211/sharing-one-grpc-proto-file-for-all-solutions/66844713#66844713). We don't need the project file, we don't want to run build/restore to pack non-dotnet files.

**Comment by Steinblock** [comment]
As described here: https://github.com/NuGet/Home/issues/4254#issuecomment-831985439

I have a backend asp.net project and a frontend vue project.

I pack the frontend in a single nuget package via a CI/CD pipeline that only needs to contain content files (html/js/css). The backend project uses this package to serve the files from `wwwroot`.

With .net 4.x I could just use `nuget.exe pack` and a `nuspec` file for that.

Now my frontend is build in a linux docker container with `npm build` so I want to use `dotnet pack` with the same `nuspec` file which is not possible without a project.

**Comment by aronweiler** [comment]
I have a CI/CD system that dynamically produces NuGet packages, and we don't want to modify CSPROJ files!

**Comment by dzuerrer** [comment]
We have 3rd party software that is made available only as .dlls. Currently we use nuget.exe to package them as nuget packages and reference them in our projects.
If dotnet nuget supported this, we could use our linux build environment to do this instead of the windows developer machines.

**Comment by csdahlberg** [comment]
My scenario is that I want to build a single analyzers NuGet package that targets multiple versions of Roslyn. It needs to contain `analyzers/dotnet/roslyn2.6/cs/Analyzer.dll`, `analyzers/dotnet/roslyn3.8/cs/Analyzer.dll`, etc., each variant built from the same project but with different properties set.

As far as I can tell, the authoring experience (mentioned in https://github.com/dotnet/sdk/issues/20355#issuecomment-909279878) for this scenario still has not [yet] been implemented.

I threw together some PowerShell scripts that fit my needs, including one to build a NuGet package from a .nuspec file: https://gist.github.com/csdahlberg/56e482c6ab28f93680bef3879c6473b0

**Comment by zivkan** [comment]
Just an FYI to the people in the thread who say they want to just use the `dotnet` CLI, a workaround is to use the MSBuild pack `NuspecFile` property: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file

It's not perfect, I'm not proposing this as a "solution" to avoid implementing the proposed feature. I'm just saying that using features that have been shipping for multiple years, it's possible to pack a nuspec using only the .NET SDK CLI.

It can be scripted by running `dotnet new classlib` in an empty folder, then `dotnet pack -p:NuspecFile=/path/to/your.nuspec -o /path/to/outputDirectory/`. There are of course many more options, like committing the csproj to source control, specifying `NuspecFile` in the project file's `<PropertyGroup>`, perhaps using `Sdk="Microsoft.Build.NoTargets"` (although the docs propose a different solution to avoid building the project).

**Comment by davezhouwa** [comment]
In our case, we have used nuget pack to create packages without requiring a csproj file.   We have close to 100 repositories doing this way.   As we are looking into the new mariner docker 2.0 image,  we found mono is required to make it work. However, mono is not available.

Our repositories are mainly Python based and for AI & Machine learning,  the production system requires shipping the artifacts through nuget format.  Having every repository creating a dummy csproj is a non trivial task.  

Bringing back a previously function which worked before and for a large set of cases is highly desirable.

We tried above approach suggested by @zivkan above and it didn't work.

**Comment by tebeco** [comment]
sounds like a perfect opportunity to create an `nuproj` @zivkan 
with MSBuild support and defacto feature parity with csproj + dotnet pack out of the box

which also would allow dotnet/nuget team to continue killing `nuspec` files and `nuget.exe`

**Comment by Nirmal4G** [comment]
> which also would allow dotnet/nuget team to continue killing `nuspec` files and `nuget.exe`

Removing `nuspec` files won't happen as they are what defines a NuGet package!

**Comment by tebeco** [comment]
not really no.
they are one way to define it
when you run `dotnet pack` on a csproj you don't explicitly have a nuspec file and you don't need it

nuspec is inherently bad if you try to integrate your build system with msbuild
which is what the current `dotnet pack` + csproj fix

the remaining issue is bundling static content like raw dll for example.

as per my first sentence, getting a an `nuproj` could leverage on all the existing msbuild integration already done by nuget team and just don't call the c# compiler but still produce an output nupkg

in all that a nuspec is not / was not / would not be necessary to exists

**Comment by Steinblock** [comment]
Correct me if I'm wrong but I think the `csproj` creates a `nuspec` file under the hood anyway.
Eventually the `nuspec` file is copied to the `nuget` package and holds the metadata. So we still need it.

Maybe someone can tell if the creation of the `nuget` package itself is just based on the `nuspec` file (which would be possible IMHO) or the `csproj` file is needed internally.

But I agree. There shouldn't be a dedicated `nuget.exe`  that I as a developer need to call but it should be possible to just use `dotnet pack` with the right arguments to trigger a `nuget` package build from a  `nuspec` file.

Just one thing I would like to mention. 

I use the [replacement tokens](https://learn.microsoft.com/en-us/nuget/reference/nuspec#replacement-tokens) (`$id$, $version$`) a lot. 

With `nuget.exe` I could just use `nuget pack -properties <name>=<value>;<name>=<value>`

With dotnet core and a `csproj` file I need to use

```
<PropertyGroup>
    <NuSpecProperties>version=$(Version);owner=itsamemario</NuSpecProperties>
</PropertyGroup>
``` 

The `dotnet pack ...  -p:Version=1.2.3 -properties "version=$(Version);owner=itsamemario"` should be possible, too.

Or just allow to directly use properties instead of the replacement tokens in a nuspec file. So

```
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
```

Could be rewritten to

```
  <metadata>
    <id>$(id)</id>
    <version>$(Version)</version>
```

**Comment by tebeco** [comment]
> With dotnet core and a csproj file I need to use
> ```xml
> <PropertyGroup>
>     <NuSpecProperties>version=$(Version);owner=itsamemario</NuSpecProperties>
> </PropertyGroup>
> ```

Why not one of the existing:
* `dotnet pack /p:Version=1.2.3-rc1` 
* `dotnet pack /p:VersionPrefix=1.2.3 /p:VersionSuffix=rc1` 
* `dotnet pack`
  ```xml
  <Version>1.2.3-rc1</Version>
  ```
* `dotnet pack`
  ```xml
  <VersionPrefix>1.2.3</VersionPrefix>
  <VersionSuffix>rc1</VersionSuffix>
  ```
https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

![image](https://user-images.githubusercontent.com/2266487/221180170-16641155-33aa-4c00-835f-4860be466bae.png)

**Comment by tebeco** [comment]
this message above is why I mentionned there's already some MSBuild integration in place with `csproj` and that something like `nuproj` and not calling the C# compiler would probably be really near to what already exists today

The fact that internally it generates a data model in shape A or B (and/or a `nuspec`) is irrelevant as a consumer.

* what's the consumer/user experience today ?
  => `dotnet pack`
* is `nuspec` ported to `dotnet pack` ?
  => no
* should we assume `dotnet pack` on `csproj` internally generate ANOTHER file format AND THEN another trasnfo for `nupkg` ?
  => I sincerly don't know.
  but that does not sound like a good assumption.
  The nuget client is already C# code from `Nuget.Client`, which is what's being (partially?) pulled into `dotnet` CLI.
* does `dotnet pack` already have code to read MsBuild logic and map that to existing data for packaging ?
  => yes, see previous message
* do we need a `nuspec` ?
  => no

What's needed is a way to "arbitrary pack" ... "stuff" like static content / raw file / etc ...
if `dotnet` CLI already leverage heavy lifting and MsBuild Stuff for `csproj` today.
I'm guessing reading the same `PropertyGroup` from the same MsBuild Engine with the same code would souns relativly possible.

The benefits of that would be to have that included in Visual Studio ... directly "as a project" for example
you would be able to run `dotnet build` and `dotnet pack` on that SLN ... IF YOU HAVE ONE
and it would properly continue to Generate and do Authoring with stuff like:
`Directory.Build.props` or `OutputPackageFolder` or Unified `Version` from your CI etc ...

and just like it's already working today, having an `nuproj` would have `dotnet pack` work on it just like you have `nuget pack` on `nuspec`

That's what my many post above are trying to point out.

moving back to `nuspec` again, would definitly make "legacy" works, but it's still legacy.
We'd loose the msbuild tooling integration with EnvVar / Props / CI / Scaffolding etc ...

The issue with nuspec is that it require dedicated tooling/toolset to automate fields change inside

I'm hinting at a solution that would somehow be in the middle of `nuspec` and `csproj` which ... even if my hope/expectation are low, I think it would answer many concerns here.
I also suspect that nuget team could also, with the help of the community write a tool like `dotnet nuget convert` and change a `nuspec` to a `nuproj` and call it a day


as you can see:
these 2 step should be what the `nuproj` would have to fix to try achieving what's asked in this issue
![image](https://user-images.githubusercontent.com/2266487/221182674-5c9671ea-7667-4c7c-8529-2ad12ca29f8a.png)
https://github.com/NuGet/Home/issues/4254#issuecomment-277034421

and as many mentionned it, since it's about not calling C# SDK / ....
it probably would be what SDK and not Proj file are for:
```xml
<Project Sdk="SomethingSomething.Nuget">
</Project>
```

**Comment by Nirmal4G** [comment]
> Correct me if I'm wrong but I think the `csproj` creates a `nuspec` file under the hood anyway. Eventually the `nuspec` file is copied to the `nuget` package and holds the metadata. So we still need it. — @Steinblock

@tebeco What he said!!!

**Comment by Nirmal4G** [comment]
Maybe you don't want to depend on NuSpec when you're building from a project file but that's our preference and not a requirement for the design of the package under the hood.

May be we can abstract it away using an MSBuild SDK like I did (e.g., `NuGet.Packaging.Sdk`) but that seems a long stretch of a request for the team! But one that, I definitely want it.

**Comment by pgolinski** [comment]
We have third party native dlls that we want to pack as nuget. Installing the nuget adds copying the dlls to output on build. I don't need csproj for that. I was sure I can pack a nuget from nuspec with `dotnet pack`. I was very much wrong

**Comment by wardboumans** [comment]
Guess this is still not possible?

**Comment by kris-vista** [comment]
This is frustrating
We were using nuget in Azure devops on a ubuntu vm to package and publish files.
Ubuntu has now removed the deprecated mono so nuget.exe doesnt work and the migration path is to use `dotnet pack`
I was expecting there might be some arguments differences between `dotnet pack` and `nuget pack` but apparently I now need to create a `.csproj` file for every nuget package I want to package up?

**Comment by MaceWindu** [comment]
You don't need csproj for each nuget, just one empty csproj file like we do [here](https://github.com/linq2db/linq2db/blob/master/NuGet/empty/empty.csproj)

```ps
# call once
dotnet restore empty/empty.csproj

# call for each nuspec you need to pack
dotnet pack empty/empty.csproj --no-build -p:NuspecFile=my.nuspec
```

But agree, taking into account that it is satisfied by empty file, it shouldn't be a task that require so much discussion for 8 years.

**Comment by Mrxx99** [comment]
@MaceWindu but that will generate a DLL, right? What if you don't want a DLL generated?

**Comment by reduckted** [comment]
@MaceWindu Neat trick. Shame you have to run a restore first, but it's definitely a useful workaround.

@Mrxx99 No DLL is generated because of the `--no-build` argument, and even if you leave that argument out, the DLL won't end up in the package unless the `.nuspec` file has a `<file>` entry to include it.

**Comment by kris-vista** [comment]
> You don't need csproj for each nuget, just one empty csproj file like we do [here](https://github.com/linq2db/linq2db/blob/master/NuGet/empty/empty.csproj)
> 
> # call once
> dotnet restore empty/empty.csproj
> 
> # call for each nuspec you need to pack
> dotnet pack empty/empty.csproj --no-build -p:NuspecFile=my.nuspec
> But agree, taking into account that it is satisfied by empty file, it shouldn't be a task that require so much discussion for 8 years.

Thanks @MaceWindu That has worked nicely!

**Comment by reillysiemens** [comment]
The [`NuGetCommand@2`](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2) Azure Pipelines task [does not support Ubuntu 24 out of the box](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#migrating-to-net-cli-on-ubuntu) and directs users to use the `dotnet` CLI directly if possible. However, folks who've been the `pack` command with that task on projects that don't require a `.csproj` file are likely to run into a spot of trouble trying to use `dotnet`.

Creating a dummy `.csproj` file and having to do a `dotnet restore` beforehand feel like unnecessary friction to a customers. Further, where `NuGetCommand@2` customers are directed to the `dotnet` CLI it says that where your scenario is not supported you should open an issue with .NET CLI team. Since this issue has been unresolved since 2017 that might cause additional customer frustration.

**Comment by reduckted** [comment]
Please reopen. #14383 only added a proposal and did not implement this feature.
