### ISSUE TITLE
Pack or extract of package does not preserve timestamps on file attributes

### ISSUE THREAD

**Issue by BlairPaine** [NuGet/Home#5240]
When I pack or unpack (install) with nuget it does not preserve the timestamps on included files.  For example the date created and date modified attributes.  I can see files in my package have been stamped with the date and time of package creation.

Were the changes for the above issues fixed and merged correctly?

Appears to be related/replica of:
[NuGet do not honor time-stamps when unpacking nupkg files #420](https://github.com/NuGet/Home/issues/420)
[Set proper file timestamp when copying from unzipped folder #188](https://github.com/NuGet/NuGet.Client/pull/188)

## Details about Problem
NuGet.exe version = 4.1.0.2450 (also tried 3.3.0.212 and 3.4.4.1321)
.NET version = 4.6.01590
OS version = Windows Server 2012 R2 (6.3.9600)
Worked before? = Not for me.

## Detailed repro steps so we can see the same problem
nuget.exe pack <path to nuspec> -Version <version number> -OutputDirectory <output dir>
nuget.exe install <package name> -Source <source dir> -OutputDirectory <output dir>

**Comment by mirecg** [comment]
Hi, I'm having the same requirements like you and like most users out there.

I'm using nuget 3.5.0.1938 and my experience is little bit different.
For me install command respects the file timestamps and extracts files with the correct timestamp. This seems that was fixed in #420.
But the problem remains in pack command, which sets the timestamps to the current time for all packed files. So the fix of install command doesn't have desired effect.

**Comment by pepone** [comment]
Hi,

Seems part of the problem is how the Zip entries are created in [PackageBuilder.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L720 ) one possible fix is to set the [LastWriteTime](https://msdn.microsoft.com/en-us/library/system.io.compression.ziparchiveentry.lastwritetime(v=vs.110).aspx) using the time from the file with the given path.

**Comment by BlairPaine** [comment]
Thanks for the feedback.  Can anyone tell me how I can get a NuGet developer to look into this and fix?

**Comment by rocker8942** [comment]
Hi, 

I have the same issue. @mirecg seems pointed out exact spot.  Can anyone help on this?

**Comment by mishra14** [comment]
it seems that https://github.com/NuGet/NuGet.Client/pull/188 did not fix this. Tagging @rohit21agrawal for visibility.
